dist: xenial

language:
  - c
  - cpp

addons:
  apt:
    packages:
      - gstreamer1.0-plugins-base
      - libgstreamer1.0-dev
      - meson

script:
  - echo "test"
branches:
  only:
    - master
